name: Simulate_Long-running_Process

on:
  workflow_call

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Perform_mock_tests
        shell: bash
        run: |
          START=$(date)
          echo "Long-running testing started at $START"
          sleep 120
          FINISH=$(date)
          echo "Long-running testing finished at $FINISH"
