name: Simulate_Long-running_Process

on:
  workflow_call

jobs:
  log-start:
    runs-on: local
    steps:
      - name: get-start
        id: start-date
        run: echo "::set-output name=date::$(date)"
       
      - name: log-start
        uses: DamianReeves/write-file-action@master
        with:
          path: E:\Experiment\ephemeral_log.txt
          write-mode: append
          contents: "Starting ephemeral long-running task @ ${{ steps.start-date.outputs.date }}"
         
  run-test:
    needs: log-start
    runs-on: ubuntu-latest
    steps:
      - name: Perform_mock_tests
        shell: bash
        run: |
          sleep 120
          
  log-end:
    needs: run-test
    runs-on: local
    steps:
      - name: get-end
        id: end-date
        run: echo "::set-output name=date::$(date)"
       
      - name: log-start
        uses: DamianReeves/write-file-action@master
        with:
          path: E:\Experiment\ephemeral_log.txt
          write-mode: append
          contents: "Finished ephemeral long-running task @ ${{ steps.end-date.outputs.date }}"
