name: Simulate_Tests

on:
  workflow_call:
    inputs:
      environment:
        description: The name of the environment being simulated
        type: string
        required: true

jobs:
  run-test:
    runs-on: local
    steps:
      - name: get-start
        id: start-date
        run: echo "::set-output name=date::$(date)"

      - name: log-start
        uses: DamianReeves/write-file-action@master
        with:
          path: E:\Experiment\static_log.txt
          write-mode: append
          contents: "Starting ${{ inputs.environment}} testing (static) @ ${{ steps.start-date.outputs.date }}"
      
      - name: Perform_mock_tests
        shell: powershell
        run: |
          Start-Sleep -Seconds 30
          
      - name: get-end
        id: end-date
        run: echo "::set-output name=date::$(date)"
        
      - name: log-end
        uses: DamianReeves/write-file-action@master
        with:
          path: E:\Experiment\static_log.txt
          write-mode: append
          contents: "Finished ${{ inputs.environment}} testing (static) @ ${{ steps.end-date.outputs.date }}"

  
