name: Simulate_Long-running_Process

on:
  workflow_call

jobs:
  run-test:
    runs-on: local
    steps:
      - name: Perform_mock_tests
        shell: powershell
        run: |
          $START = Get-Date
          echo "Long-running testing started at $START"
          Start-Sleep -Seconds 120
          $FINISH = Get-Date
          echo "Long-running testing finished at $FINISH"

  log-long-running-finish:
    needs: run-test
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - name: checkout-repo
        uses: actions/checkout@v3

      - name: get-date
        id: start-date
        run: echo "::set-output name=date::$(date)"
        
      - name: log-entry
        uses: DamianReeves/write-file-action@master
        with: 
          path: ./logs/static_log.txt
          write-mode: append
          contents: "Long running process finished @ ${{ steps.start-date.outputs.date }}\n"

      - name: commit-log-entry
        uses: stefanzweifel/git-auto-commit-action@v5
        with: 
          branch: main
          commit_message: "Update logs @ ${{ steps.start-date.outputs.date }}"
          push_options: '--force'
