name: Standard_Tests_Ephemeral

# Simuulates running 3 sets of tests in succession, each having their own environment

on: 
  workflow_dispatch

jobs:
  log-SIT-call:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v3

      - name: get-date
        id: start-date
        run: echo "::set-output name=date::$(date)"
        
      - name: first-log-entry
        uses: DamianReeves/write-file-action@master
        with: 
          path: ./logs/ephemeral_log.txt
          write-mode: overwrite
          contents: "Ephemeral workflow started @ ${{ steps.start-date.outputs.date }}"
    
      - name: log-entry
        uses: DamianReeves/write-file-action@master
        with: 
          path: ./logs/ephemeral_log.txt
          write-mode: append
          contents: "Starting SIT Tests @ ${{ steps.start-date.outputs.date }}"  

      - name: commit-log-entry
        uses: Andro999b/push@v1.3
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
          message: "Update logs @ ${{ steps.start-date.outputs.date }}"
               
  run-SIT-tests:
    needs: log-SIT-call
    uses: ./.github/workflows/[REUSABLE]-ephemeral-tests.yml
    with:
      environment: SIT
      
  log-UAT-call:
    runs-on: ubuntu-latest
    needs: run-SIT-tests
    steps:
      - name: checkout-repo
        uses: actions/checkout@v3

      - name: get-date
        id: start-date
        run: echo "::set-output name=date::$(date)"
        
      - name: log-entry
        uses: DamianReeves/write-file-action@master
        with: 
          path: ./logs/ephemeral_log.txt
          write-mode: append
          contents: "Starting SIT Tests @ ${{ steps.start-date.outputs.date }}"

      - name: commit-log-entry
        uses: Andro999b/push@v1.3
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
          message: "Update logs @ ${{ steps.start-date.outputs.date }}"
  
  log-long-running-start:
    runs-on: ubuntu-latest
    needs: run-SIT-tests
    steps:
      - name: checkout-repo
        uses: actions/checkout@v3

      - name: get-date
        id: start-date
        run: echo "::set-output name=date::$(date)"
        
      - name: log-entry
        uses: DamianReeves/write-file-action@master
        with: 
          path: ./logs/ephemeral_log.txt
          write-mode: append
          contents: "Starting long-running process @ ${{ steps.start-date.outputs.date }}"

      - name: commit-log-entry
        uses: Andro999b/push@v1.3
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
          message: "Update logs @ ${{ steps.start-date.outputs.date }}"
  
  start-long-running-process:
    needs: log-UAT-call
    uses: ./.github/workflows/[REUSABLE]-ephemeral-long-running.yml

  log-long-running-finish:
    needs: start-long-running-process
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v3

      - name: get-date
        id: start-date
        run: echo "::set-output name=date::$(date)"
        
      - name: log-entry
        uses: DamianReeves/write-file-action@master
        with: 
          path: ./logs/ephemeral_log.txt
          write-mode: append
          contents: "Long running process finished @ ${{ steps.start-date.outputs.date }}"

      - name: commit-log-entry
        uses: Andro999b/push@v1.3
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
          message: "Update logs @ ${{ steps.start-date.outputs.date }}"
          
  snooze:
    needs: log-UAT-call
    runs-on: ubuntu-latest
    steps:
      - name: call_sleep_timer
        shell: bash
        run: sleep 10
        
  run-UAT-tests:
    needs: snooze # this is to make sure the long-running process grabs the resource first
    uses: ./.github/workflows/[REUSABLE]-ephemeral-tests.yml
    with: 
      environment: UAT

  log-ORT-call:
    needs: run-UAT-tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v3

      - name: get-date
        id: start-date
        run: echo "::set-output name=date::$(date)"
        
      - name: log-entry
        uses: DamianReeves/write-file-action@master
        with: 
          path: ./logs/ephemeral_log.txt
          write-mode: append
          contents: "Starting ORT tests @ ${{ steps.start-date.outputs.date }}"

      - name: commit-log-entry
        uses: Andro999b/push@v1.3
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
          message: "Update logs @ ${{ steps.start-date.outputs.date }}"

  run-ORT-tests:
    needs: log-ORT-call
    uses: ./.github/workflows/[REUSABLE]-ephemeral-tests.yml
    with:
      environment: ORT

  log-ORT-end:
    needs: run-ORT-tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v3

      - name: get-date
        id: start-date
        run: echo "::set-output name=date::$(date)"
        
      - name: log-entry
        uses: DamianReeves/write-file-action@master
        with: 
          path: ./logs/ephemeral_log.txt
          write-mode: append
          contents: "Finished ORT tests @ ${{ steps.start-date.outputs.date }}"

      - name: commit-log-entry
        uses: Andro999b/push@v1.3
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
          message: "Update logs @ ${{ steps.start-date.outputs.date }}"      
