name: Standard_Tests_Static

# Simuulates running 3 sets of tests in succession, each having their own environment

on: 
  workflow_dispatch

jobs:
  log-workflow-start:
    uses: ./.github/workflows/[REUSABLE]-write-log.yml
    with:
      message: "Static workflow started @ "
      is_static: true
      
  log-SIT-call:
    needs: log-workflow-start 
    uses: ./.github/workflows/[REUSABLE]-write-log.yml
    with:
      message: "SIT testing started @ "
      is_static: true 
      
  run-SIT-tests:
    needs: log-SIT-call
    uses: ./.github/workflows/[REUSABLE]-static-tests.yml
    with:
      environment: SIT
      
  log-UAT-call:
    needs: run-SIT-tests
    uses: ./.github/workflows/[REUSABLE]-write-log.yml
    with:
      message: "Starting SIT Tests @ "
      is_static: true
  
  log-long-running-start:
    needs: run-SIT-tests
    uses: ./.github/workflows/[REUSABLE]-write-log.yml
    with:
      message: "Starting long-running process @ "
      is_static: true
           
  start-long-running-process:
    needs: log-long-running-start
    uses: ./.github/workflows/[REUSABLE]-static-long-running.yml
    secrets: inherit

  snooze:
    needs: log-UAT-call
    runs-on: ubuntu-latest
    steps:
      - name: call_sleep_timer
        shell: bash
        run: sleep 10
        
  run-UAT-tests:
    needs: snooze # this is to make sure the long-running process grabs the resource first
    uses: ./.github/workflows/[REUSABLE]-static-tests.yml
    with: 
      environment: UAT

  log-ORT-call:
    needs: run-UAT-tests
    uses: ./.github/workflows/[REUSABLE]-write-log.yml
    with:
      message: "Starting ORT tests @ "
      is_static: true
      
  run-ORT-tests:
    needs: log-ORT-call
    uses: ./.github/workflows/[REUSABLE]-static-tests.yml
    with:
      environment: ORT

  log-ORT-end:
    needs: run-ORT-tests 
    uses: ./.github/workflows/[REUSABLE]-write-log.yml
    with:
      message: "Finished ORT tests @ "
      is_static: true
